title: Tankman.dev
description: A starter template for Tankman's docs.
theme: just-the-docs

url: /tankman.dev

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
